#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

cd "$script_dir" || exit

compose() {
  docker compose "$@"
}

composer() {
  compose exec drupal composer "$@"
}

drush() {
  compose exec drupal vendor/bin/drush "$@"
}

# Extract the module path from the service.
module_path=$(compose run --rm drupal sh -c 'echo $MODULE_PATH')


compose down --remove-orphans
compose pull
compose up --detach --remove-orphans --wait
composer config --no-plugins allow-plugins true
composer config extra.merge-plugin.include "$module_path/composer.json"
composer require drush/drush wikimedia/composer-merge-plugin
# Reset Drupal installation
compose exec drupal sh -c 'find . -name .ht.sqlite -ls -delete; rm web/sites/default/settings.php' || true
drush site:install --db-url='sqlite://sites/default/files/.ht.sqlite?module=sqlite' --yes
drush pm:install azure_ad_delta_sync
compose exec drupal php web/core/scripts/generate-proxy-class.php 'Drupal\azure_ad_delta_sync\UserManager' "$module_path/src"
compose exec drupal php web/core/scripts/generate-proxy-class.php 'Drupal\azure_ad_delta_sync\Controller' "$module_path/src"
compose down --remove-orphans
