name: PHP code analysis

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  php-code-analysis:
    name: PHP code analysis
    runs-on: ubuntu-latest
    strategy:
      matrix:
        drupal-version:
          - 10
          # Installing with sqlite does not yet work with Drupal 11 (cf. https://github.com/docker-library/drupal/issues/264)
          # - 11
    steps:
      - uses: actions/checkout@v4
      - name: Code analysis
        run: |
           DRUPAL_VERSION=${{ matrix.drupal-version }} ./scripts/code-analysis
